[[layer:Default]]
[role=group,includesConstraints="layer:*",includesConcepts="layer:*"]
== Layer

This chapter describes the concepts and constraints related to the layered package structure of the application.

=== Concepts

[[layer:Layer]]
.The application has a layered structure. Each layer is represented by a package located in the root package and labeled as `Layer`.
[plantuml,layer,role=concept]
----
@startuml
skinparam componentStyle uml2

artifact " " as Main <<Main>> <<Artifact>>
package "{fqn:'com.github.dmn1k.todos.adapter'}" as Adapter <<Package>>
package "{fqn:'com.github.dmn1k.todos.adapter.input'}" as InputAdapter <<Package>><<(+)Layer>><<(+)Adapter>><<(+)Input>>
package "{fqn:'com.github.dmn1k.todos.adapter.output'}" as OutputAdapter <<Package>><<(+)Layer>><<(+)Adapter>><<(+)Output>>
package "{fqn:'com.github.dmn1k.todos.adapter.persistence'}" as PersistenceAdapter <<Package>><<(+)Layer>><<(+)Adapter>><<(+)Output>><<(+)Persistence>>
package "{fqn:'com.github.dmn1k.todos.domain'}" as Domain <<Package>>
package "{fqn:'com.github.dmn1k.todos.domain.api'}" as DomainApi <<Package>><<(+)Layer>><<(+)Domain>><<(+)API>>
package "{fqn:'com.github.dmn1k.todos.domain.impl'}" as DomainImpl <<Package>><<(+)Layer>><<(+)Domain>><<(+)Implementation>>
package "{fqn:'com.github.dmn1k.todos.domain.ports'}" as DomainPorts <<Package>><<(+)Layer>><<(+)Domain>><<(+)Ports>>

Main -> Adapter :               :CONTAINS
Main -> Domain :                :CONTAINS
Adapter -> InputAdapter :       :CONTAINS
Adapter -> OutputAdapter :      :CONTAINS
Adapter -> PersistenceAdapter : :CONTAINS
Domain -> DomainApi :           :CONTAINS
Domain -> DomainImpl :          :CONTAINS
Domain -> DomainPorts :         :CONTAINS

@enduml
----


[[layer:LayerDependency]]
[source,cypher,role=concept,requiresConcepts="layer:Layer",reportType="csv"]
.A dependency between two layers exists if there are dependencies between Java types in any of the sub-packages. These are represented by `DEPENDS_ON` relations.
----
MATCH
  (layer1:Layer:Package)-[:CONTAINS*]->(type1:Type),
  (layer2:Layer:Package)-[:CONTAINS*]->(type2:Type),
  (type1)-[d:DEPENDS_ON]->(type2)
WHERE
  layer1 <> layer2
WITH
  layer1, layer2, count(d) as weight
MERGE
  (layer1)-[d:DEPENDS_ON]->(layer2)
SET
  d.weight = weight
RETURN
  layer1 as Dependent, layer2 as Dependency, weight as Weight
----

[[layer:LayerDependencyDefinition]]
[plantuml,layerdeps,role=concept,requiresConcepts="layer:Layer"]
.The dependencies between layers are represented by `DEFINES_DEPENDENCY` relations.
----
@startuml
skinparam componentStyle uml2

[Domain-API] as domainapi                   <<Domain>> <<API>>
[Domain-Impl] as domainimpl                 <<Domain>> <<Implementation>>
[Domain-Ports] as domainports               <<Domain>> <<Ports>>
[Output-Adapter] as outputadapter           <<Adapter>> <<Output>>
[Input-Adapter] as inputadapter             <<Adapter>> <<Input>>
[Persistence-Adapter] as persistenceadapter <<Adapter>> <<Output>> <<Persistence>>


inputadapter       -d-> domainapi    : (+):DEFINES_DEPENDENCY
domainimpl         -d-> domainapi    : (+):DEFINES_DEPENDENCY
domainimpl         -d-> domainports  : (+):DEFINES_DEPENDENCY
domainports        -u-> domainapi    : (+):DEFINES_DEPENDENCY
outputadapter      -u-> domainports  : (+):DEFINES_DEPENDENCY
outputadapter      -u-> domainapi    : (+):DEFINES_DEPENDENCY
persistenceadapter -u-> domainimpl   : (+):DEFINES_DEPENDENCY

@enduml
----

=== Constraints

[[layer:LayerDependencyViolation]]
[source,cypher,role=constraint,requiresConcepts="layer:LayerDependency,layer:LayerDependencyDefinition",primaryReportColumn="Type",severity=blocker]
.There must be no dependencies between layers that are not explicitly defined.
----
MATCH
  (layer1:Layer)-[:DEPENDS_ON]->(layer2:Layer)
WHERE NOT
  (layer1)-[:DEFINES_DEPENDENCY]->(layer2)
WITH
  layer1, layer2
MATCH
  (layer1)-[:CONTAINS*]->(type1:Type),
  (layer2)-[:CONTAINS*]->(type2:Type),
  (type1)-[:DEPENDS_ON]->(type2)
RETURN
  layer1.name as Layer, type1 as Type, layer2.name as LayerDependency, type2 as TypeDependency
----

=== Reports

[[layer:LayerDependencyDiagram]]
[source,cypher,role=concept,requiresConcepts="layer:LayerDependency",reportType="plantuml-component-diagram"]
.Diagram about existing dependencies between layers.
----
MATCH
  (layer:Layer)
OPTIONAL MATCH
  (layer)-[dependsOn:DEPENDS_ON]->(:Layer)
RETURN
  *
----

[[layer:LayerDependency.graphml]]
[source,cypher,role=concept,requiresConcepts="layer:LayerDependency",reportType="graphml"]
.GraphML report about dependencies between layers and their contained types.
----
MATCH
  (layer:Layer:Package)-[:CONTAINS*]->(type:Type)
OPTIONAL MATCH
  (type)-[dependsOn:DEPENDS_ON]->(:Type)
RETURN {
  role : "graph",
  parent : layer,
  nodes : collect(type),
  relationships : collect(dependsOn)
} as TypesPerLayer
----
